apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
